### PR TITLE
Updated Test Automation Framework to 2023.10

### PR DESCRIPTION
**Pull request by AlinaCapotaUiPath**
Updated Dependencies and small improvements

### CODE REVIEW

**Comment by bebef1987** [comment]
Please update .local folder content to the same versions we use in the project

**Comment by AlinaCapotaUiPath** [comment]
@bebef1987 done. Please approve if no other changes are required.

**Review by bebef1987 — APPROVED** [review]
All looks OK

**Comment by bebef1987** [comment]
Merging with approval

**Pull request merged**
